#FROM alpine@sha256:30ebbffae9ba098b9c345b890c6610aa8422f067754d7e707978a954f3b7a601 as builder
FROM alpine as builder

RUN apk update && apk upgrade && apk add xz

WORKDIR /

RUN wget http://repo.voidlinux.eu/static/xbps-static-latest.x86_64-musl.tar.xz && \
    tar xvf /xbps-static-latest.x86_64-musl.tar.xz && \
    rm /xbps-static-latest.x86_64-musl.tar.xz && \
    mkdir /tmp/rootfs
    
RUN yes | XBPS_ARCH=x86_64-musl xbps-install --yes --rootdir /tmp/rootfs --repository=http://muslrepo.voidlinux.eu/current -S base-voidstrap

FROM scratch

COPY --from=builder /tmp/rootfs /

ENV TERM=xterm

RUN xbps-install --sync --update --yes && \
    xbps-install --sync --update --yes && \
    xbps-alternatives --set bash && \
    rm -rv /var/cache/xbps/* && \
    mv /etc/profile.d/colorls.sh /etc/profile.d/colorls.sh-disabled

CMD [ "/bin/bash",  "-l" ]