#!/usr/bin/env pwsh
@{
Title="GNU Patch"
Description=@'
Patch is a program that applies changes to files based on differences laid out as by the program
diff. The changes may be applied to one or more files depending on the contents of the diff file.
It accepts several different diff formats. It may also be used to revert previously applied
differences.
'@

Name='patch'
Version='2.7.6'

Home=@('https://www.gnu.org/software/patch/')
Upstream='https://ftpmirror.gnu.org/gnu/$Name/$Name-$Version.tar.gz'
}
