#!/bin/bash

mkdir -p /tmp/root
XBPS_ARCH=x86_64-musl xbps-install --yes --rootdir /tmp/root --repository=http://muslrepo.voidlinux.eu/current -S base-voidstrap

#XBPS_ARCH=x86_64-musl xbps-install -y --rootdir /tmp/root --repository=http://muslrepo.voidlinux.eu/current -S base-voidstrap
#mkdir docker-void
#tar -pC docker-void -c . | docker import - <REPOSITORY NAME>
#rm -rf docker-void
